modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="gizliavci"
version="1.0.0"
displayName="Gizli Avcı"
description='''
Bir oyuncu gizli avcı olarak seçilir, diğerleri hayatta kalmaya çalışır!
'''